// generated by the Eye Compiler v0.1
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

struct Point {
	int32_t x;
	int32_t y;
};

int main() {
	int32_t x = 2;
	int32_t y = 3;
	struct Point p = (struct Point){ .x = x, .y = y };
	printf("%d\n", p.x);
	printf("%d\n", p.y);
	return 0;
}

