// generated by the Eye Compiler v0.1
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

struct Point {
  int32_t x;
  int32_t y;
};

int main() {
  int32_t x = 0;
  int32_t y = 0;
  struct Point p = (struct Point){.x = x, .y = y};
  printf("%d\n", p.x);
  printf("%d\n", p.y);
  return 0;
}
