//! `cargo xtask` - workspace automation.
//!
//! `cargo xtask codegen` reads `crates/ast/eye.ungram` and regenerates
//! `crates/ast/src/generated.rs`: the structural typed-AST layer over the
//! rowan CST. the generated file is committed; rerun this whenever the
//! grammar changes.

use std::path::{Path, PathBuf};
use std::process::Command;

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use ungrammar::{Grammar, Rule};

fn main() {
    match std::env::args().nth(1).as_deref() {
        Some("codegen") => codegen(),
        _ => {
            eprintln!("usage: cargo xtask codegen");
            std::process::exit(1);
        }
    }
}

/// repo root - `crates/xtask` is two levels down from it.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("xtask lives at <root>/crates/xtask")
        .to_path_buf()
}

fn codegen() {
    let root = repo_root();
    let ungram_path = root.join("crates/ast/eye.ungram");
    let out_path = root.join("crates/ast/src/generated.rs");

    let text = std::fs::read_to_string(&ungram_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", ungram_path.display()));
    let grammar: Grammar = text.parse().expect("eye.ungram failed to parse");

    std::fs::write(&out_path, generate(&grammar)).expect("write generated.rs");

    let ok = Command::new("rustfmt")
        .arg(&out_path)
        .status()
        .expect("run rustfmt")
        .success();
    assert!(ok, "rustfmt failed on {}", out_path.display());

    println!("regenerated {}", out_path.display());
}

// ---- field model ----

/// what a node field resolves to in the generated accessor.
enum FieldTy {
    /// a child node of the named kind.
    Node(String),
    /// a direct child token. in the v0.1 grammar every labelled token is an
    /// identifier, so the accessor always looks up `SyntaxKind::Ident`.
    Token,
}

struct Field {
    /// accessor name - from the ungrammar label, or derived from the type.
    label: Option<String>,
    ty: FieldTy,
    /// true for a `Node*` repetition.
    rep: bool,
}

/// flatten a rule into the flat field list its node accessors are built from.
fn walk(g: &Grammar, rule: &Rule, label: Option<&str>, out: &mut Vec<Field>) {
    match rule {
        Rule::Labeled { label, rule } => walk(g, rule, Some(label), out),
        Rule::Node(n) => out.push(Field {
            label: label.map(str::to_string),
            ty: FieldTy::Node(g[*n].name.clone()),
            rep: false,
        }),
        // an unlabelled token (punctuation/keyword) generates no accessor
        Rule::Token(_) => {
            if let Some(l) = label {
                out.push(Field {
                    label: Some(l.to_string()),
                    ty: FieldTy::Token,
                    rep: false,
                });
            }
        }
        Rule::Rep(inner) => {
            // a label may sit inside or outside the repetition
            let (lbl, core) = match &**inner {
                Rule::Labeled { label, rule } => (Some(label.as_str()), &**rule),
                other => (label, other),
            };
            if let Rule::Node(n) = core {
                out.push(Field {
                    label: lbl.map(str::to_string),
                    ty: FieldTy::Node(g[*n].name.clone()),
                    rep: true,
                });
            }
        }
        Rule::Opt(inner) => walk(g, inner, label, out),
        Rule::Seq(rules) => rules.iter().for_each(|r| walk(g, r, None, out)),
        // an alternation inside a node body is the all-token `Literal` case -
        // no structural accessors
        Rule::Alt(_) => {}
    }
}

/// if `rule` is an alternation of plain node references, return their names -
/// this node is a typed `enum`.
fn as_enum(g: &Grammar, rule: &Rule) -> Option<Vec<String>> {
    let Rule::Alt(alts) = rule else { return None };
    let mut names = Vec::with_capacity(alts.len());
    for alt in alts {
        match alt {
            Rule::Node(n) => names.push(g[*n].name.clone()),
            _ => return None,
        }
    }
    Some(names)
}

// ---- code generation ----

fn generate(grammar: &Grammar) -> String {
    let items = grammar.iter().map(|node| {
        let data = &grammar[node];
        match as_enum(grammar, &data.rule) {
            Some(variants) => gen_enum(&data.name, &variants),
            None => {
                let mut fields = Vec::new();
                walk(grammar, &data.rule, None, &mut fields);
                gen_node(&data.name, &fields)
            }
        }
    });
    let body = quote! { #(#items)* };
    format!(
        "//! Generated by `cargo xtask codegen` from crates/ast/eye.ungram.\n\
         //! do not edit by hand - edit the grammar and regenerate.\n\n\
         use syntax::{{SyntaxKind, SyntaxNode, SyntaxToken}};\n\n\
         use crate::{{support, AstChildren, AstNode}};\n\n{body}\n",
    )
}

fn gen_node(name: &str, fields: &[Field]) -> TokenStream {
    let ident = format_ident!("{name}");
    let accessors = gen_accessors(fields);
    quote! {
        #[derive(Debug, Clone, PartialEq, Eq, Hash)]
        pub struct #ident {
            pub(crate) syntax: SyntaxNode,
        }

        impl AstNode for #ident {
            fn can_cast(kind: SyntaxKind) -> bool {
                kind == SyntaxKind::#ident
            }
            fn cast(syntax: SyntaxNode) -> Option<Self> {
                if syntax.kind() == SyntaxKind::#ident {
                    Some(Self { syntax })
                } else {
                    None
                }
            }
            fn syntax(&self) -> &SyntaxNode {
                &self.syntax
            }
        }

        impl #ident {
            #accessors
        }
    }
}

fn gen_accessors(fields: &[Field]) -> TokenStream {
    let mut out = TokenStream::new();
    for (i, f) in fields.iter().enumerate() {
        let ty = match &f.ty {
            FieldTy::Token => {
                let m = format_ident!("{}", f.label.clone().expect("token field is labelled"));
                out.extend(quote! {
                    pub fn #m(&self) -> Option<SyntaxToken> {
                        support::token(&self.syntax, SyntaxKind::Ident)
                    }
                });
                continue;
            }
            FieldTy::Node(ty) => ty,
        };
        let ty_id = format_ident!("{ty}");
        if f.rep {
            let m = format_ident!(
                "{}",
                f.label.clone().unwrap_or_else(|| format!("{}s", snake(ty)))
            );
            out.extend(quote! {
                pub fn #m(&self) -> AstChildren<#ty_id> {
                    support::children(&self.syntax)
                }
            });
            continue;
        }
        // single child node. if the same node type appears more than once in
        // this node (e.g. `BinExpr = lhs:Expr rhs:Expr`), accessors must pick
        // by position rather than by first-of-kind.
        let same: Vec<usize> = fields
            .iter()
            .enumerate()
            .filter(|(_, g)| matches!(&g.ty, FieldTy::Node(t) if t == ty) && !g.rep)
            .map(|(j, _)| j)
            .collect();
        let m = format_ident!("{}", f.label.clone().unwrap_or_else(|| snake(ty)));
        if same.len() > 1 {
            let idx = same.iter().position(|&j| j == i).unwrap();
            let idx = proc_macro2::Literal::usize_unsuffixed(idx);
            out.extend(quote! {
                pub fn #m(&self) -> Option<#ty_id> {
                    support::children(&self.syntax).nth(#idx)
                }
            });
        } else {
            out.extend(quote! {
                pub fn #m(&self) -> Option<#ty_id> {
                    support::child(&self.syntax)
                }
            });
        }
    }
    out
}

fn gen_enum(name: &str, variants: &[String]) -> TokenStream {
    let ident = format_ident!("{name}");
    let vars: Vec<_> = variants.iter().map(|v| format_ident!("{v}")).collect();
    quote! {
        #[derive(Debug, Clone, PartialEq, Eq, Hash)]
        pub enum #ident {
            #(#vars(#vars)),*
        }

        impl AstNode for #ident {
            fn can_cast(kind: SyntaxKind) -> bool {
                matches!(kind, #(SyntaxKind::#vars)|*)
            }
            fn cast(syntax: SyntaxNode) -> Option<Self> {
                let res = match syntax.kind() {
                    #(SyntaxKind::#vars => #ident::#vars(#vars { syntax }),)*
                    _ => return None,
                };
                Some(res)
            }
            fn syntax(&self) -> &SyntaxNode {
                match self {
                    #(#ident::#vars(it) => it.syntax()),*
                }
            }
        }
    }
}

/// `StructDef` -> `struct_def`.
fn snake(camel: &str) -> String {
    let mut out = String::with_capacity(camel.len() + 4);
    for (i, c) in camel.char_indices() {
        if c.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}
