use hir::core::{
    Body, Enum, Expr, ExprId, Function, HIR, Literal, Pat, Resolution, Stmt, Struct, TypeRef,
};

pub struct CGen<'a> {
    hir: &'a HIR,
    output: String,
    indent_level: usize,
}

impl<'a> CGen<'a> {
    pub fn new(hir: &'a HIR) -> Self {
        Self {
            hir,
            output: String::new(),
            indent_level: 0,
        }
    }

    pub fn gen_all(mut self) -> String {
        self.output
            .push_str("// generated by the Eye Compiler v0.2\n");
        self.output.push_str("#include <stdio.h>\n");
        self.output.push_str("#include <stdint.h>\n");
        self.output.push_str("#include <stdbool.h>\n\n");

        self.hir
            .structs
            .iter()
            .for_each(|(_id, struct_def)| self.gen_struct(struct_def));

        self.hir
            .enums
            .iter()
            .for_each(|(_id, enum_def)| self.gen_enum(enum_def));

        self.hir
            .functions
            .iter()
            .for_each(|(_id, r#fn)| self.gen_function(r#fn));

        self.output
    }

    fn push_indent(&mut self) {
        self.output.push_str(&"\t".repeat(self.indent_level));
    }

    fn map_type_ref(&self, ty: &TypeRef) -> String {
        match ty {
            TypeRef::Path(name) => match name.as_str() {
                "int32" => "int32_t".to_string(),
                "float32" => "float".to_string(),
                "float64" => "double".to_string(),
                "bool" => "bool".to_string(),
                "char" => "char".to_string(),
                "string" => "const char*".to_string(), // string literal base
                other => other.to_string(),
            },
            TypeRef::Ref(inner) => format!("{}*", self.map_type_ref(inner)),
            TypeRef::Ptr(inner) => format!("{}*", self.map_type_ref(inner)),
            TypeRef::Error => "void* /* ERROR TY */".to_string(),
        }
    }

    fn get_expr_type(&self, expr_idx: ExprId, body: &Body) -> Option<TypeRef> {
        // check the explicit type map
        if let Some(ty) = body.expr_types.get(expr_idx) {
            return Some(ty.clone());
        }

        // then try to derive it from the expression itself
        match &body.exprs[expr_idx] {
            Expr::Path(Resolution::Local(local_id)) => {
                // the local should have its type from lowering
                body.locals[*local_id].ty.clone()
            }
            Expr::Field { base, name } => {
                let parent_ty = self.get_expr_type(*base, body)?;

                let struct_name = match &parent_ty {
                    TypeRef::Path(n) => n.clone(),
                    TypeRef::Ref(inner) | TypeRef::Ptr(inner) => match inner.as_ref() {
                        TypeRef::Path(n) => n.clone(),
                        _ => return None,
                    },
                    _ => return None,
                };

                let struct_def = self
                    .hir
                    .structs
                    .iter()
                    .find(|(_, s)| s.name == struct_name)
                    .map(|(_, s)| s)?;

                for &field_id in &struct_def.fields {
                    let field = &self.hir.fields[field_id];
                    if field.name == *name {
                        return Some(field.ty.clone());
                    }
                }
                None
            }
            Expr::Ref { operand } => {
                // &expr has type Ref(inner_type)
                let inner = self.get_expr_type(*operand, body)?;
                Some(TypeRef::Ref(Box::new(inner)))
            }
            Expr::Deref { operand } => {
                // *expr has the inner type
                let op_ty = self.get_expr_type(*operand, body)?;
                match op_ty {
                    TypeRef::Ref(inner) | TypeRef::Ptr(inner) => Some(*inner),
                    _ => None,
                }
            }
            _ => None,
        }
    }

    fn gen_struct(&mut self, struct_def: &Struct) {
        self.output.push_str("typedef struct {\n");
        self.indent_level += 1;

        for &field_id in &struct_def.fields {
            let field = &self.hir.fields[field_id];
            self.push_indent();
            let ty_str = self.map_type_ref(&field.ty);
            self.output
                .push_str(&format!("{} {};\n", ty_str, field.name));
        }

        self.indent_level -= 1;
        self.output
            .push_str(&format!("}} {};\n\n", struct_def.name));
    }

    fn gen_enum(&mut self, enum_def: &Enum) {
        self.output.push_str("typedef enum {\n");
        self.indent_level += 1;
        for variant in &enum_def.variants {
            self.push_indent();
            self.output.push_str(&format!("{},\n", variant.name));
        }
        self.indent_level -= 1;
        self.output.push_str(&format!("}} {};\n\n", enum_def.name));
    }

    fn gen_function(&mut self, r#fn: &Function) {
        let ret_type = if r#fn.name == "main" {
            "int".to_string()
        } else {
            r#fn.ret
                .as_ref()
                .map_or("void".to_string(), |t| self.map_type_ref(t))
        };

        self.output
            .push_str(&format!("{} {}(", ret_type, r#fn.name));

        for (i, param) in r#fn.params.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            let p_ty = self.map_type_ref(&param.ty);
            self.output.push_str(&format!("{} {}", p_ty, param.name));
        }
        self.output.push_str(") {\n");
        self.indent_level += 1;

        if let Some(body_id) = r#fn.body {
            let body = &self.hir.bodies[body_id];
            self.gen_body(body);

            if let Some(tail_expr_idx) = body.tail {
                self.push_indent();
                if r#fn.name != "main" && r#fn.ret.is_some() {
                    self.output.push_str("return ");
                }
                self.gen_expr(tail_expr_idx, body);
                self.output.push_str(";\n");
            }
        }

        if r#fn.name == "main" {
            self.push_indent();
            self.output.push_str("return 0;\n");
        }

        self.indent_level -= 1;
        self.output.push_str("}\n\n");
    }

    pub fn gen_body(&mut self, body: &Body) {
        for &stmt_idx in &body.block {
            let stmt = &body.stmts[stmt_idx];
            self.gen_stmt(stmt, body);
        }
    }

    fn gen_stmt(&mut self, stmt: &Stmt, body: &Body) {
        match stmt {
            Stmt::Let {
                pat,
                ty,
                init,
                mutable,
            } => {
                self.push_indent();

                if !*mutable {
                    self.output.push_str("const ");
                }

                let type_str = match ty {
                    Some(t) => self.map_type_ref(t),
                    // FIXME: change once we have type inference
                    None => "/* EXPLICT TYPE MISSING */".to_string(),
                };
                let pat_node = &body.pats[*pat];
                let local_idx = match pat_node {
                    Pat::Bind(id) => *id,
                    // syntactically impossible: only Bind comes from let-pat
                    // lowering. Variant/Wildcard live in match arms; Missing
                    // means broken syntax. Skip rather than emit junk.
                    Pat::Missing | Pat::Variant { .. } | Pat::Wildcard => return,
                };
                let var_name = &body.locals[local_idx].name;
                self.output.push_str(&format!("{} {}", type_str, var_name));

                if let Some(expr_idx) = init {
                    self.output.push_str(" = ");
                    self.gen_expr(*expr_idx, body);
                }

                self.output.push_str(";\n");
            }
            Stmt::Expr(expr_idx) => {
                if let Expr::If {
                    cond: _,
                    then_branch: _,
                    else_branch: _,
                } = &body.exprs[*expr_idx]
                {
                    self.push_indent();
                    self.gen_expr(*expr_idx, body);
                    self.output.push('\n');
                } else {
                    self.push_indent();
                    self.gen_expr(*expr_idx, body);
                    self.output.push_str(";\n");
                }
            }
        }
    }

    fn gen_expr(&mut self, expr_idx: ExprId, body: &Body) {
        match &body.exprs[expr_idx] {
            Expr::Missing => self.output.push_str("/* MISSING EXPR */"),
            Expr::Literal(literal) => match literal {
                Literal::Int(val) => self.output.push_str(&val.to_string()),
                Literal::Float(val) => self.output.push_str(val.as_str()),
                Literal::String(val) => self.output.push_str(&format!("\"{}\"", val)),
                Literal::Bool(val) => self.output.push_str(if *val { "true" } else { "false" }),
                Literal::Char(val) => self.output.push_str(&format!("'{}'", val)),
            },
            Expr::Path(resolution) => match resolution {
                Resolution::Local(id) => self.output.push_str(&body.locals[*id].name),
                Resolution::Fn(id) => self.output.push_str(&self.hir.functions[*id].name),
                Resolution::Struct(id) => self.output.push_str(&self.hir.structs[*id].name),
                Resolution::Unresolved(name) => self.output.push_str(name.as_str()),
                Resolution::Variant { enum_id, idx } => {
                    let variant = &self.hir.enums[*enum_id].variants[*idx as usize];
                    self.output.push_str(&variant.name);
                }
                Resolution::Enum(_) => {
                    // HIR lowering converts bare enum-name in expr position to
                    // a diagnostic + Expr::Missing, so codegen never sees this.
                    unreachable!("Resolution::Enum reached codegen; HIR should have rejected it");
                }
            },
            Expr::StructLit { ty, fields } => {
                let ty_str = self.map_type_ref(ty);
                self.output.push_str(&format!("({}){{ ", ty_str));
                for (i, field) in fields.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.output.push_str(&format!(".{} = ", field.name));
                    self.gen_expr(field.value, body);
                }
                self.output.push_str(" }");
            }
            Expr::Call { callee, args } => {
                if let Expr::Path(Resolution::Unresolved(name)) = &body.exprs[*callee]
                    && name == "print"
                {
                    self.gen_print(args, body);
                    return;
                }
                self.gen_expr(*callee, body);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(*arg, body);
                }
                self.output.push(')');
            }
            Expr::Field { base, name } => {
                self.gen_expr(*base, body);
                let mut is_pointer_like = false;
                if let Some(base_ty) = self.get_expr_type(*base, body) {
                    is_pointer_like = matches!(base_ty, TypeRef::Ref(_) | TypeRef::Ptr(_));
                }

                if is_pointer_like {
                    self.output.push_str(&format!("->{}", name));
                } else {
                    self.output.push_str(&format!(".{}", name));
                }
            }
            Expr::Binary { op, lhs, rhs } => {
                self.output.push('(');
                self.gen_expr(*lhs, body);
                self.output.push_str(&format!(" {} ", op));
                self.gen_expr(*rhs, body);
                self.output.push(')');
            }
            Expr::Unary { op, operand } => {
                self.output.push_str(&format!("{}", op));
                self.gen_expr(*operand, body);
            }
            Expr::Block(block_id) => {
                let block = &body.blocks[*block_id];

                self.output.push_str("{\n");
                self.indent_level += 1;

                for &stmt_idx in &block.stmts {
                    let stmt = &body.stmts[stmt_idx];
                    self.gen_stmt(stmt, body);
                }

                if let Some(tail_expr_idx) = block.tail {
                    self.push_indent();
                    self.gen_expr(tail_expr_idx, body);
                    self.output.push_str(";\n");
                }

                self.indent_level -= 1;
                self.push_indent();
                self.output.push('}');
            }
            Expr::Assign { lhs, rhs } => {
                self.gen_expr(*lhs, body);
                self.output.push_str(" = ");
                self.gen_expr(*rhs, body);
            }
            Expr::If {
                cond,
                then_branch,
                else_branch,
            } => {
                let then_block = &body.blocks[*then_branch];

                // If it has an else branch AND contains no inner statements,
                // it's an expression-based ternary assignment context!
                if let Some(_else_id) = else_branch
                    && then_block.stmts.is_empty()
                    && let Some(_then_tail) = then_block.tail
                {
                    self.output.push('(');
                    self.gen_expr(*cond, body);
                    self.output.push_str(" ? ");
                    self.gen_expr(then_block.tail.unwrap(), body);
                    self.output.push_str(" : ");

                    let else_block = &body.blocks[else_branch.unwrap()];
                    if let Some(else_tail) = else_block.tail {
                        self.gen_expr(else_tail, body);
                    } else {
                        self.output.push('0');
                    }
                    self.output.push(')');
                } else {
                    // conditional control statement block
                    self.output.push_str("if (");
                    self.gen_expr(*cond, body);
                    self.output.push_str(") {\n");
                    self.indent_level += 1;

                    for &stmt_idx in &then_block.stmts {
                        let stmt = &body.stmts[stmt_idx];
                        self.gen_stmt(stmt, body);
                    }
                    if let Some(tail) = then_block.tail {
                        self.push_indent();
                        self.gen_expr(tail, body);
                        self.output.push_str(";\n");
                    }

                    self.indent_level -= 1;
                    self.push_indent();
                    self.output.push('}');

                    if let Some(else_id) = else_branch {
                        self.output.push_str(" else {\n");
                        self.indent_level += 1;
                        let else_block = &body.blocks[*else_id];
                        for &stmt_idx in &else_block.stmts {
                            let stmt = &body.stmts[stmt_idx];
                            self.gen_stmt(stmt, body);
                        }
                        if let Some(tail) = else_block.tail {
                            self.push_indent();
                            self.gen_expr(tail, body);
                            self.output.push_str(";\n");
                        }
                        self.indent_level -= 1;
                        self.push_indent();
                        self.output.push('}');
                    }
                }
            }
            Expr::Loop { body: block_id } => {
                self.output.push_str("while (true) {\n");
                self.indent_level += 1;

                let block = &body.blocks[*block_id];
                for &stmt_idx in &block.stmts {
                    let stmt = &body.stmts[stmt_idx];
                    self.gen_stmt(stmt, body);
                }
                if let Some(tail) = block.tail {
                    self.push_indent();
                    self.gen_expr(tail, body);
                    self.output.push_str(";\n");
                }
                self.indent_level -= 1;
                self.push_indent();
                self.output.push('}');
            }
            Expr::Break => self.output.push_str("break"),
            Expr::Continue => self.output.push_str("continue"),
            Expr::Ref { operand } => {
                self.output.push('&');
                self.gen_expr(*operand, body);
            }
            Expr::Deref { operand } => {
                self.output.push('(');
                self.output.push('*');
                self.gen_expr(*operand, body);
                self.output.push(')');
            }
            Expr::Match { .. } => {
                // M5 lowers match via Strategy A (statement-level hoist with a
                // `_matchN` temp + `switch`). Until then, emit a placeholder so
                // the build stays green and any accidental use is visible.
                self.output.push_str("/* MATCH (M5) */");
            }
        }
    }

    fn gen_print(&mut self, args: &[ExprId], body: &Body) {
        self.output.push_str("printf(");

        let Some(format_str_idx) = args.first() else {
            self.output.push(')');
            return;
        };

        // Non-literal format string: emit as-is, no `{}` substitution.
        let Expr::Literal(Literal::String(s)) = &body.exprs[*format_str_idx] else {
            self.gen_expr(*format_str_idx, body);
            for arg in args.iter().skip(1) {
                self.output.push_str(", ");
                self.gen_expr(*arg, body);
            }
            self.output.push(')');
            return;
        };

        // Substitute each `{}` with a per-arg format specifier driven by the
        // value's HIR type. Args without a matching placeholder are still
        // forwarded so libc surfaces an arity warning at C-compile time.
        let value_args = &args[1..];
        let mut value_iter = value_args.iter();
        let mut rendered = String::with_capacity(s.len() + value_args.len() * 2);
        let bytes = s.as_bytes();
        let mut i = 0;
        while i < bytes.len() {
            if i + 1 < bytes.len() && bytes[i] == b'{' && bytes[i + 1] == b'}' {
                let spec = value_iter
                    .next()
                    .map(|&a| self.format_spec_for(a, body))
                    .unwrap_or("%d");
                rendered.push_str(spec);
                i += 2;
            } else {
                rendered.push(bytes[i] as char);
                i += 1;
            }
        }
        self.output.push_str(&format!("\"{}\\n\"", rendered));

        for arg in value_args {
            self.output.push_str(", ");
            self.gen_expr(*arg, body);
        }
        self.output.push(')');
    }

    /// Pick a printf specifier for `arg` based on its HIR type. Falls back to
    /// literal-kind inspection when no `expr_types` entry exists (literals
    /// don't get one today).
    fn format_spec_for(&self, arg: ExprId, body: &Body) -> &'static str {
        if let Expr::Literal(lit) = &body.exprs[arg] {
            return match lit {
                Literal::Int(_) => "%d",
                Literal::Float(_) => "%f",
                Literal::String(_) => "%s",
                Literal::Bool(_) => "%d",
                Literal::Char(_) => "%c",
            };
        }
        match self.get_expr_type(arg, body) {
            Some(ty) => Self::spec_for_type(&ty),
            None => "%d",
        }
    }

    fn spec_for_type(ty: &TypeRef) -> &'static str {
        match ty {
            TypeRef::Path(name) => match name.as_str() {
                "int32" => "%d",
                // printf promotes float to double for variadics, so a single
                // `%f` covers both surface types.
                "float32" | "float64" => "%f",
                "bool" => "%d",
                "char" => "%c",
                "string" => "%s",
                // Unknown nominal type (likely a struct): no sensible printf
                // representation, but we still emit *something* so codegen
                // does not silently drop the placeholder.
                _ => "%d",
            },
            TypeRef::Ref(_) | TypeRef::Ptr(_) => "%p",
            TypeRef::Error => "%d",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ast::{AstNode, SourceFile};
    use hir::core::lower_source_file;
    use lexer::{Lexer, SourceText};

    fn emit(src: &str) -> String {
        let source = SourceText::new(src.to_string());
        let tokens = Lexer::new(&source).tokenize().tokens;
        let parse = parser::parse(&tokens, &source);
        assert!(parse.errors.is_empty(), "parse errors: {:?}", parse.errors);
        let file = SourceFile::cast(parse.green).expect("root is SourceFile");
        let hir = lower_source_file(file);
        assert!(
            hir.diagnostics.is_empty(),
            "hir diagnostics: {:?}",
            hir.diagnostics
        );
        CGen::new(&hir).gen_all()
    }

    /// Canonical `main.eye`. Pinning the C output cements the v0.1 codegen
    /// behaviour - any incidental change downstream forces a snapshot
    /// review.
    #[test]
    fn main_eye_c_output_snapshot() {
        let src = "\
structure Point {
    int32 x,
    int32 y,
};

main() {
    const int32 x = 0;
    const int32 y = 0;
    var Point p = Point { x, y };

    print(\"{}\", p.x);
    print(\"{}\", p.y);
}
";
        insta::assert_snapshot!(emit(src));
    }

    /// Regression for the call-arg emission bug: the loop used to guard
    /// `gen_expr` behind `if i > 0`, dropping arg 0 for every non-`print`
    /// call. The v0.1 parser has no fn-call-with-args path outside
    /// `print(...)`, so we build the HIR directly and feed it into the
    /// expression generator.
    #[test]
    fn user_fn_call_emits_every_argument_in_order() {
        use hir::core::{Body, Expr, Function, HIR, Literal, Resolution, Stmt};

        let mut hir = HIR::default();

        let callee_fn = hir.functions.alloc(Function {
            name: "add".into(),
            params: Vec::new(),
            ret: None,
            body: None,
        });

        let mut body = Body::default();
        let callee = body.exprs.alloc(Expr::Path(Resolution::Fn(callee_fn)));
        let a1 = body.exprs.alloc(Expr::Literal(Literal::Int(1)));
        let a2 = body.exprs.alloc(Expr::Literal(Literal::Int(2)));
        let a3 = body.exprs.alloc(Expr::Literal(Literal::Int(3)));
        let call = body.exprs.alloc(Expr::Call {
            callee,
            args: vec![a1, a2, a3],
        });
        let call_stmt = body.stmts.alloc(Stmt::Expr(call));
        body.block.push(call_stmt);
        let body_id = hir.bodies.alloc(body);

        let main_fn = hir.functions.alloc(Function {
            name: "main".into(),
            params: Vec::new(),
            ret: None,
            body: Some(body_id),
        });
        hir.items.functions.insert("main".into(), main_fn);
        hir.items.functions.insert("add".into(), callee_fn);

        let c = CGen::new(&hir).gen_all();
        assert!(
            c.contains("add(1, 2, 3)"),
            "expected `add(1, 2, 3)` in output, got:\n{c}"
        );
        assert!(
            !c.contains("add(, "),
            "leading separator should not appear, got:\n{c}"
        );
    }

    /// Regression for nested field access: the HIR previously used
    /// `NameRef::nth(1)`, which returns `None` when the base is itself
    /// a `FieldExpr`. The C output should contain the chained `.y`.
    #[test]
    fn nested_field_access_lowers_correctly() {
        let src = "\
structure Inner {
    int32 y,
};

structure Outer {
    Inner i,
};

main() {
    const Inner i = Inner { y: 42 };
    const Outer o = Outer { i: i };
    print(\"{}\", o.i.y);
}
";
        let c = emit(src);
        assert!(
            c.contains("o.i.y"),
            "expected chained field access `o.i.y` in output, got:\n{c}"
        );
    }

    /// Reference type in a fn param plus the address-of prefix at the call
    /// site. Auto-deref turns `v.x` inside the callee into `v->x` in C.
    #[test]
    fn reference_and_pointer_codegen_v02() {
        let src = "\
structure Vector {
    int32 x,
    int32 y,
};

update_vector(&Vector v) {
    -- Eye auto-dereferences references for field access
    print(\"{}\", v.x);
}

main() {
    var Vector vec = Vector { x: 10, y: 20 };
    -- Pass by reference
    update_vector(&vec);
}
";
        let c_output = emit(src);

        // 1. parameter type lowers to a pointer
        assert!(
            c_output.contains("update_vector(Vector* v)"),
            "expected `update_vector(Vector* v)` in output, got:\n{c_output}"
        );
        // 2. auto-deref translates `.` to `->` on a ref-typed base
        assert!(
            c_output.contains("v->x"),
            "expected `v->x` in output, got:\n{c_output}"
        );
        // 3. address-of expression translation
        assert!(
            c_output.contains("update_vector(&vec)"),
            "expected `update_vector(&vec)` in output, got:\n{c_output}"
        );
    }

    /// Each primitive arg in a `print(...)` should map to its correct printf
    /// specifier. Previously every `{}` lowered to `%d`, so strings, floats,
    /// chars, and pointers came out garbled.
    #[test]
    fn print_format_specifiers_match_primitive_types() {
        let src = "\
main() {
    const int32 i = 7;
    const float64 f = 3.14;
    const bool b = true;
    const char c = 'x';
    print(\"i={} f={} b={} c={}\", i, f, b, c);
    print(\"lit s={} lit i={} lit f={} lit b={} lit c={}\", \"hi\", 1, 2.5, false, 'q');
}
";
        let c = emit(src);
        assert!(
            c.contains("\"i=%d f=%f b=%d c=%c\\n\""),
            "expected per-type specifiers for typed locals, got:\n{c}"
        );
        assert!(
            c.contains("\"lit s=%s lit i=%d lit f=%f lit b=%d lit c=%c\\n\""),
            "expected literal-driven specifiers, got:\n{c}"
        );
    }

    /// A `&T`-typed value should print with `%p` rather than the default
    /// `%d`, otherwise the C compiler issues a format-mismatch warning.
    #[test]
    fn print_format_specifier_for_reference_is_pointer() {
        let src = "\
structure P { int32 x, };

main() {
    var P p = P { x: 1 };
    var &P r = &p;
    print(\"{}\", r);
}
";
        let c = emit(src);
        assert!(
            c.contains("\"%p\\n\""),
            "expected `%p` specifier for reference value, got:\n{c}"
        );
    }
}
