//! Codegen: HIR -> C source.
//!
//! A single linear `output: String` is built top-down with an `indent_level`.
//! There is no buffering; value-position matches are the one exception and are
//! hoisted ahead of their enclosing statement (see [`matches`]).
//!
//! The generator is split by concern, one method group per file:
//! - [`types`]: type and format-specifier mapping (`map_type_ref`,
//!   `get_expr_type`, `spec_for_type`).
//! - [`items`]: top-level declarations (struct, enum, function, body).
//! - [`stmt`]: statement codegen.
//! - [`expr`]: expression codegen.
//! - [`print`]: the `print` intrinsic and its `{}` -> printf lowering.
//! - [`matches`]: `match` lowering - statement-position `switch` plus the
//!   value-position hoist into `_matchN` temps.
//!
//! This file holds the [`CGen`] aggregate, its constructor, the top-level
//! `gen_all` driver, and the shared `push_indent` helper. The public path
//! stays `codegen::core::CGen`.

mod expr;
mod items;
mod matches;
mod print;
mod stmt;
mod types;

#[cfg(test)]
mod tests;

use hir::core::{ExprId, HIR};
use rustc_hash::FxHashMap;

pub struct CGen<'a> {
    hir: &'a HIR,
    output: String,
    indent_level: usize,
    match_temps: FxHashMap<ExprId, String>,
    match_counter: usize,
}

impl<'a> CGen<'a> {
    pub fn new(hir: &'a HIR) -> Self {
        Self {
            hir,
            output: String::new(),
            indent_level: 0,
            match_temps: FxHashMap::default(),
            match_counter: 0,
        }
    }

    pub fn gen_all(mut self) -> String {
        self.output
            .push_str("// generated by the Eye Compiler v0.3\n");
        self.output.push_str("#include <stdio.h>\n");
        self.output.push_str("#include <stdint.h>\n");
        self.output.push_str("#include <stdbool.h>\n\n");

        self.hir
            .structs
            .iter()
            .for_each(|(_id, struct_def)| self.gen_struct(struct_def));

        self.hir
            .enums
            .iter()
            .for_each(|(_id, enum_def)| self.gen_enum(enum_def));

        self.hir
            .functions
            .iter()
            .for_each(|(_id, r#fn)| self.gen_function(r#fn));

        self.output
    }

    fn push_indent(&mut self) {
        self.output.push_str(&"\t".repeat(self.indent_level));
    }
}
