//! MIR -> C emitter: the dumb printer.
//!
//! This is the Track 2 codegen, the only path since the Segment 5 cutover (it
//! replaced the HIR-walking emitter). It walks a [`MirBody`] and prints C, one
//! construct to one C form, making no semantic decisions (control-flow
//! flattening and temp generation already happened in `mir::lower`). The driver
//! seam is `src/backend.rs`; the oracle is program output, not C text.

use super::arrays::{array_wrapper_name, collect_program_arrays};
use super::types::{CDeclarator, CType, spec_for_type};
use hir::core::{Enum, Function, HIR, Literal, Struct, TypeRef, Union};
use mir::core::{MirBlock, MirBody, MirStmt, Operand, Place, RValue, SwitchArm, Type};
use mir::lower::lower_function;
use std::borrow::Cow;
use std::fmt::Write as _;

/// Generate a complete C translation unit from the HIR via MIR.
pub fn gen_mir(hir: &HIR) -> String {
    MirGen::new(hir).gen_all()
}

struct MirGen<'a> {
    hir: &'a HIR,
    output: String,
    indent: usize,
    local_names: Vec<String>,
}

enum IndexAccess {
    ArrayValue,
    ArrayPointer,
    Direct,
}

impl<'a> MirGen<'a> {
    fn new(hir: &'a HIR) -> Self {
        Self {
            hir,
            output: String::new(),
            indent: 0,
            local_names: Vec::new(),
        }
    }

    fn gen_all(mut self) -> String {
        self.output
            .push_str("// generated by the Eye Compiler v0.7 (MIR path)\n");
        self.output.push_str("#include <stdio.h>\n");
        self.output.push_str("#include <stdint.h>\n");
        self.output.push_str("#include <stddef.h>\n");
        self.output.push_str("#include <stdbool.h>\n\n");

        // Nominal type declarations, in dependency order: structs and unions
        // first, then enums, then the fixed-array value wrappers (an array of a
        // struct needs the struct complete).
        for (_, s) in self.hir.structs.iter() {
            self.gen_struct(s);
        }
        for (_, u) in self.hir.unions.iter() {
            self.gen_union(u);
        }
        for (_, e) in self.hir.enums.iter() {
            self.gen_enum(e);
        }
        self.gen_array_typedefs();

        let extern_fns = self.hir.functions.iter().filter(|(_, f)| f.is_extern);
        for (_, f) in extern_fns {
            self.gen_function(f);
        }
        let defined_fns = self.hir.functions.iter().filter(|(_, f)| !f.is_extern);
        for (_, f) in defined_fns {
            self.gen_function(f);
        }

        self.output
    }

    fn push_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push('\t');
        }
    }

    fn gen_function(&mut self, r#fn: &Function) {
        if r#fn.is_extern {
            match &r#fn.ret {
                Some(ret) => self.w(format_args!("{} {}(", CType::new(ret), r#fn.name)),
                None => self.w(format_args!("void {}(", r#fn.name)),
            }
            self.comma_params(r#fn, false);
            self.output.push_str(");\n");
            return;
        }

        if r#fn.name == "main" {
            self.w(format_args!("int {}(", r#fn.name));
        } else {
            match &r#fn.ret {
                Some(ret) => self.w(format_args!("{} {}(", CType::new(ret), r#fn.name)),
                None => self.w(format_args!("void {}(", r#fn.name)),
            }
        }
        self.comma_params(r#fn, true);
        self.output.push_str(") {\n");
        self.indent += 1;

        if let Some(body_id) = r#fn.body {
            let body = &self.hir.bodies[body_id];
            // `main` returns `int` but its body tail (if any) is discarded and
            // the emitter supplies `return 0`, so it lowers as a void body.
            let ret = if r#fn.name == "main" {
                None
            } else {
                r#fn.ret.clone()
            };
            let mir = lower_function(self.hir, body, r#fn.params.len(), ret);
            self.local_names = Self::local_names(&mir);
            self.gen_block(&mir, &mir.body);
            self.local_names.clear();
        }

        if r#fn.name == "main" {
            self.push_indent();
            self.output.push_str("return 0;\n");
        }

        self.indent -= 1;
        self.output.push_str("}\n\n");
    }

    fn comma_params(&mut self, r#fn: &Function, with_names: bool) {
        for (i, param) in r#fn.params.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            if with_names {
                self.w(format_args!("{} {}", CType::new(&param.ty), param.name));
            } else {
                self.w(format_args!("{}", CType::new(&param.ty)));
            }
        }
    }

    fn gen_block(&mut self, mir: &MirBody, block: &MirBlock) {
        for stmt in &block.stmts {
            self.gen_stmt(mir, stmt);
        }
    }

    fn gen_stmt(&mut self, mir: &MirBody, stmt: &MirStmt) {
        match stmt {
            MirStmt::Let { local, init } => {
                self.push_indent();
                let l = &mir.locals[*local];
                if !l.mutable {
                    self.output.push_str("const ");
                }
                let name = local_name(&self.local_names, *local);
                self.output
                    .write_fmt(format_args!("{}", CDeclarator::new(&l.ty, name)))
                    .expect("writing to String cannot fail");
                if let Some(rv) = init {
                    self.output.push_str(" = ");
                    self.gen_rvalue(mir, rv);
                }
                self.output.push_str(";\n");
            }
            MirStmt::Assign { place, value } => {
                self.push_indent();
                self.gen_place(mir, place);
                self.output.push_str(" = ");
                self.gen_rvalue(mir, value);
                self.output.push_str(";\n");
            }
            MirStmt::Eval(rv) => {
                self.push_indent();
                self.gen_rvalue(mir, rv);
                self.output.push_str(";\n");
            }
            MirStmt::Return(op) => {
                self.push_indent();
                self.output.push_str("return");
                if let Some(op) = op {
                    self.output.push(' ');
                    self.gen_operand(mir, op);
                }
                self.output.push_str(";\n");
            }
            MirStmt::If {
                cond,
                then_block,
                else_block,
            } => {
                self.push_indent();
                self.output.push_str("if (");
                self.gen_operand(mir, cond);
                self.output.push_str(") {\n");
                self.indent += 1;
                self.gen_block(mir, then_block);
                self.indent -= 1;
                self.push_indent();
                self.output.push('}');
                if let Some(else_block) = else_block {
                    self.output.push_str(" else {\n");
                    self.indent += 1;
                    self.gen_block(mir, else_block);
                    self.indent -= 1;
                    self.push_indent();
                    self.output.push('}');
                }
                self.output.push('\n');
            }
            MirStmt::Loop { body } => {
                self.push_indent();
                self.output.push_str("while (true) {\n");
                self.indent += 1;
                self.gen_block(mir, body);
                self.indent -= 1;
                self.push_indent();
                self.output.push_str("}\n");
            }
            MirStmt::Switch {
                scrut,
                arms,
                default,
            } => self.gen_switch(mir, scrut, arms, default),
            MirStmt::Break => {
                self.push_indent();
                self.output.push_str("break;\n");
            }
            MirStmt::Continue => {
                self.push_indent();
                self.output.push_str("continue;\n");
            }
        }
    }

    /// Render a [`MirStmt::Switch`] as an `if`/`else if` chain comparing the
    /// scrutinee tag against each variant, not as a C `switch`. A C `switch`
    /// would capture a `break` that a match arm intends for an enclosing loop;
    /// an `if` chain leaves `break`/`continue` bound to the loop. The scrutinee
    /// is a trivial operand, so re-evaluating it per arm has no side effect.
    fn gen_switch(
        &mut self,
        mir: &MirBody,
        scrut: &Operand,
        arms: &[SwitchArm],
        default: &Option<MirBlock>,
    ) {
        let mut first = true;
        for arm in arms {
            self.push_indent();
            self.output
                .push_str(if first { "if (" } else { "else if (" });
            first = false;
            self.gen_operand(mir, scrut);
            let label =
                &self.hir.enums[arm.variant.enum_id].variants[arm.variant.idx as usize].name;
            self.w(format_args!(" == {}) {{\n", label));
            self.indent += 1;
            self.gen_block(mir, &arm.body);
            self.indent -= 1;
            self.push_indent();
            self.output.push_str("}\n");
        }
        if let Some(default) = default {
            self.push_indent();
            // `else { ... }` after variant arms; a bare block for a
            // wildcard-only match (no preceding `if`).
            self.output.push_str(if first { "{\n" } else { "else {\n" });
            self.indent += 1;
            self.gen_block(mir, default);
            self.indent -= 1;
            self.push_indent();
            self.output.push_str("}\n");
        }
    }

    fn gen_enum(&mut self, e: &Enum) {
        self.output.push_str("typedef enum {\n");
        self.indent += 1;
        for variant in &e.variants {
            self.push_indent();
            self.w(format_args!("{},\n", variant.name));
        }
        self.indent -= 1;
        self.w(format_args!("}} {};\n\n", e.name));
    }

    fn gen_struct(&mut self, s: &Struct) {
        self.output.push_str("typedef struct {\n");
        self.indent += 1;
        for &field_id in &s.fields {
            let field = &self.hir.fields[field_id];
            self.push_indent();
            self.w(format_args!("{} {};\n", CType::new(&field.ty), field.name));
        }
        self.indent -= 1;
        self.w(format_args!("}} {};\n\n", s.name));
    }

    // Same shape as `gen_struct`, emitting `union` for overlapping storage.
    fn gen_union(&mut self, u: &Union) {
        self.output.push_str("typedef union {\n");
        self.indent += 1;
        for &field_id in &u.fields {
            let field = &self.hir.fields[field_id];
            self.push_indent();
            self.w(format_args!("{} {};\n", CType::new(&field.ty), field.name));
        }
        self.indent -= 1;
        self.w(format_args!("}} {};\n\n", u.name));
    }

    /// Emit a `typedef struct { T data[N]; }` for every distinct array type in
    /// the program (the struct-wrap value representation). Shares the collection
    /// with the HIR-walk path, so both emitters declare the same wrapper set.
    fn gen_array_typedefs(&mut self) {
        let ordered = collect_program_arrays(self.hir);
        if ordered.is_empty() {
            return;
        }
        self.output
            .push_str("// fixed-array value wrappers (struct-wrap representation)\n");
        for wrapper in ordered {
            self.w(format_args!(
                "typedef struct {{ {} data[{}]; }} {};\n",
                CType::new(&wrapper.elem),
                wrapper.len,
                wrapper.name
            ));
        }
        self.output.push('\n');
    }

    fn gen_rvalue(&mut self, mir: &MirBody, rv: &RValue) {
        match rv {
            RValue::Use(op) => self.gen_operand(mir, op),
            RValue::Binary(op, a, b) => {
                self.output.push('(');
                self.gen_operand(mir, a);
                self.w(format_args!(" {} ", op));
                self.gen_operand(mir, b);
                self.output.push(')');
            }
            RValue::Unary(op, operand) => {
                self.w(format_args!("{}", op));
                self.gen_operand(mir, operand);
            }
            RValue::Cast(operand, ty) => {
                self.w(format_args!("({})", CType::new(ty)));
                self.gen_operand(mir, operand);
            }
            RValue::Ref(place) => {
                self.output.push('&');
                self.gen_place(mir, place);
            }
            RValue::Deref(operand) => {
                self.output.push_str("(*");
                self.gen_operand(mir, operand);
                self.output.push(')');
            }
            RValue::Print { args } => self.gen_print(mir, args),
            RValue::Variant(v) => {
                let label = &self.hir.enums[v.enum_id].variants[v.idx as usize].name;
                self.w(format_args!("{}", label));
            }
            RValue::Call { func, args } => {
                let name = &self.hir.functions[*func].name;
                self.w(format_args!("{}(", name));
                for (i, a) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_operand(mir, a);
                }
                self.output.push(')');
            }
            // A value array is a compound literal of its wrapper struct:
            // `(__eye_arr_T_N){{ a, b, c }}` - the outer brace is the struct,
            // the inner initializes its `data[N]`. The type is carried on the
            // node, so unlike the HIR path there is no type-recovery fallback:
            // the emitter trusts the lowering (R2 / I2).
            RValue::ArrayLit { ty, elems } => {
                let TypeRef::Array { elem, len } = ty else {
                    unreachable!("ArrayLit rvalue carries a non-array type: {ty:?}");
                };
                self.w(format_args!("({}){{{{ ", array_wrapper_name(elem, *len)));
                for (i, el) in elems.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_operand(mir, el);
                }
                self.output.push_str(" }}");
            }
            RValue::StructLit { ty, fields } => {
                self.w(format_args!("({}){{ ", CType::new(ty)));
                for (i, (name, value)) in fields.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.w(format_args!(".{} = ", name));
                    self.gen_operand(mir, value);
                }
                self.output.push_str(" }");
            }
        }
    }

    fn gen_operand(&mut self, mir: &MirBody, op: &Operand) {
        match op {
            Operand::Const(lit) => self.gen_literal(lit),
            Operand::Copy(place) => self.gen_place(mir, place),
        }
    }

    fn gen_place(&mut self, mir: &MirBody, place: &Place) {
        match place {
            Place::Local(id) => {
                self.output.push_str(local_name(&self.local_names, *id));
            }
            // Arrays are wrapper structs, so indexing reaches through `data`. A
            // value array uses `.data[i]`; a reference or pointer to an array
            // uses `->data[i]`; a raw pointer indexes directly. The decision is
            // driven by the base place's type (`place_type`).
            Place::Index(base, index) => {
                self.gen_place(mir, base);
                match self.index_access(mir, base) {
                    IndexAccess::ArrayValue => self.output.push_str(".data["),
                    IndexAccess::ArrayPointer => self.output.push_str("->data["),
                    IndexAccess::Direct => self.output.push('['),
                }
                self.gen_operand(mir, index);
                self.output.push(']');
            }
            // A field through a reference or pointer auto-derefs to `->`; a
            // field on a value uses `.`.
            Place::Field(base, name) => {
                self.gen_place(mir, base);
                if self.place_is_pointer_like(mir, base) {
                    self.w(format_args!("->{}", name));
                } else {
                    self.w(format_args!(".{}", name));
                }
            }
            Place::Deref(base) => {
                self.output.push_str("(*");
                self.gen_place(mir, base);
                self.output.push(')');
            }
        }
    }

    fn gen_literal(&mut self, lit: &Literal) {
        match lit {
            Literal::Int(v) => self.w(format_args!("{}", v)),
            Literal::Float(s) => self.output.push_str(s.as_str()),
            Literal::String(s) => self.w(format_args!("\"{}\"", s)),
            Literal::Bool(b) => self.output.push_str(if *b { "true" } else { "false" }),
            Literal::Char(c) => self.w(format_args!("'{}'", c)),
        }
    }

    /// The `print` intrinsic, lowered to `printf` with a per-argument specifier
    /// substituted for each `{}`. Mirrors the old HIR-path `gen_print`
    /// (`super::print`) but reads operand types instead of HIR expression types.
    fn gen_print(&mut self, mir: &MirBody, args: &[Operand]) {
        self.output.push_str("printf(");
        let Some((fmt, values)) = args.split_first() else {
            self.output.push(')');
            return;
        };

        let Operand::Const(Literal::String(s)) = fmt else {
            // Non-literal format string: forward operands unchanged.
            self.gen_operand(mir, fmt);
            for v in values {
                self.output.push_str(", ");
                self.gen_operand(mir, v);
            }
            self.output.push(')');
            return;
        };

        let mut value_iter = values.iter();
        let mut rendered = String::with_capacity(s.len() + values.len() * 2);
        let mut chars = s.chars().peekable();
        while let Some(c) = chars.next() {
            if c == '{' && chars.peek() == Some(&'}') {
                chars.next();
                let spec = value_iter
                    .next()
                    .map(|op| self.operand_spec(mir, op))
                    .unwrap_or("%d");
                rendered.push_str(spec);
            } else if c == '%' {
                rendered.push_str("%%");
            } else {
                rendered.push(c);
            }
        }
        self.w(format_args!("\"{}\\n\"", rendered));
        for v in values {
            self.output.push_str(", ");
            self.gen_operand(mir, v);
        }
        self.output.push(')');
    }

    fn operand_spec(&self, mir: &MirBody, op: &Operand) -> &'static str {
        match op {
            Operand::Const(Literal::Int(_)) => "%d",
            Operand::Const(Literal::Float(_)) => "%f",
            Operand::Const(Literal::String(_)) => "%s",
            Operand::Const(Literal::Bool(_)) => "%d",
            Operand::Const(Literal::Char(_)) => "%c",
            Operand::Copy(place) => spec_for_type(self.place_type(mir, place).as_ref()),
        }
    }

    /// Recover the type of a place from `MirLocal.ty` plus the HIR struct/union
    /// definitions. Total (REDESIGN I2): it always returns a [`Type`], never
    /// rejects. A projection whose type cannot be resolved (only reachable on a
    /// malformed input the front end would already have diagnosed) falls back to
    /// [`TypeRef::Error`], which the callers (the `.`/`->` and `.data[]`
    /// decisions, the printf specifier) handle without panicking.
    fn place_type<'b>(&'b self, mir: &'b MirBody, place: &'b Place) -> Cow<'b, Type> {
        match place {
            Place::Local(id) => Cow::Borrowed(&mir.locals[*id].ty),
            Place::Field(base, name) => self.field_type(mir, base, name),
            // `a[i]` has the element type of an array base, or the pointee of a
            // reference/raw-pointer base.
            Place::Index(base, _) => match self.place_type(mir, base) {
                Cow::Borrowed(TypeRef::Array { elem, .. }) => Cow::Borrowed(elem.as_ref()),
                Cow::Borrowed(TypeRef::Ref(inner) | TypeRef::Ptr(inner)) => match inner.as_ref() {
                    TypeRef::Array { elem, .. } => Cow::Borrowed(elem.as_ref()),
                    other => Cow::Borrowed(other),
                },
                Cow::Borrowed(other) => Cow::Borrowed(other),
                Cow::Owned(TypeRef::Array { elem, .. }) => Cow::Owned(*elem),
                Cow::Owned(TypeRef::Ref(inner) | TypeRef::Ptr(inner)) => match *inner {
                    TypeRef::Array { elem, .. } => Cow::Owned(*elem),
                    other => Cow::Owned(other),
                },
                Cow::Owned(other) => Cow::Owned(other),
            },
            // `*p` has the pointee type.
            Place::Deref(base) => match self.place_type(mir, base) {
                Cow::Borrowed(TypeRef::Ref(inner) | TypeRef::Ptr(inner)) => {
                    Cow::Borrowed(inner.as_ref())
                }
                Cow::Borrowed(other) => Cow::Borrowed(other),
                Cow::Owned(TypeRef::Ref(inner) | TypeRef::Ptr(inner)) => Cow::Owned(*inner),
                Cow::Owned(other) => Cow::Owned(other),
            },
        }
    }

    fn index_access(&self, mir: &MirBody, place: &Place) -> IndexAccess {
        match self.place_type(mir, place).as_ref() {
            TypeRef::Array { .. } => IndexAccess::ArrayValue,
            TypeRef::Ref(inner) | TypeRef::Ptr(inner)
                if matches!(inner.as_ref(), TypeRef::Array { .. }) =>
            {
                IndexAccess::ArrayPointer
            }
            _ => IndexAccess::Direct,
        }
    }

    fn place_is_pointer_like(&self, mir: &MirBody, place: &Place) -> bool {
        matches!(
            self.place_type(mir, place).as_ref(),
            TypeRef::Ref(_) | TypeRef::Ptr(_)
        )
    }

    /// The declared type of field `name` on the (possibly reference/pointer)
    /// struct or union that `base` resolves to. Structs and unions share the
    /// field arena, so a union member resolves the same way.
    fn field_type<'b>(
        &'b self,
        mir: &'b MirBody,
        base: &'b Place,
        name: &hir::core::Text,
    ) -> Cow<'b, Type> {
        let base_ty = self.place_type(mir, base);
        let struct_name = match base_ty.as_ref() {
            TypeRef::Path(n) => n,
            TypeRef::Ref(inner) | TypeRef::Ptr(inner) => match inner.as_ref() {
                TypeRef::Path(n) => n,
                _ => return Cow::Owned(TypeRef::Error),
            },
            _ => return Cow::Owned(TypeRef::Error),
        };
        let field_id = self
            .hir
            .items
            .structs
            .get(struct_name)
            .and_then(|&id| self.hir.structs[id].field_index.get(name).copied())
            .or_else(|| {
                self.hir
                    .items
                    .unions
                    .get(struct_name)
                    .and_then(|&id| self.hir.unions[id].field_index.get(name).copied())
            });
        match field_id {
            Some(id) => Cow::Borrowed(&self.hir.fields[id].ty),
            None => Cow::Owned(TypeRef::Error),
        }
    }

    /// The C name for a local. Parameters keep their bare source name (the
    /// function signature declares them by that name). Every other local - a
    /// `let` binding or a generated temp - is suffixed with its [`LocalId`], so
    /// two same-named `let`s in one C scope (same-block shadowing) cannot
    /// collide into a redeclaration. MIR's locals arena gives each a unique id;
    /// suffixing surfaces it. This is output-invariant (it only renames), so it
    /// is safe to do now and closes the totality hole before cutover.
    fn local_names(mir: &MirBody) -> Vec<String> {
        let mut names = Vec::with_capacity(mir.locals.len());
        for (id, local) in mir.locals.iter() {
            let raw = u32::from(id.into_raw());
            let idx = raw as usize;
            if names.len() <= idx {
                names.resize(idx + 1, String::new());
            }
            names[idx] = if mir.params.contains(&id) {
                // A parameter always has a source name; the signature uses it bare.
                local
                    .name
                    .as_ref()
                    .expect("parameter has a source name")
                    .to_string()
            } else {
                match &local.name {
                    Some(name) => format!("{}_{}", name, raw),
                    None => format!("_t{}", raw),
                }
            };
        }
        names
    }

    fn w(&mut self, args: std::fmt::Arguments<'_>) {
        self.output
            .write_fmt(args)
            .expect("writing to String cannot fail");
    }
}

fn local_name(names: &[String], id: mir::core::LocalId) -> &str {
    let raw = u32::from(id.into_raw()) as usize;
    names.get(raw).expect("MIR local name was precomputed")
}
