//! shared diagnostic vocabulary for the eye compiler front-end.
//!
//! every producing layer (lexer, parser, hir) defines its own typed *kind*
//! enum - the single source of truth for an error - and implements
//! [`Diagnostic`] for it. the prose message comes from [`std::fmt::Display`]
//! (generated by `thiserror` on each kind enum), never stored as the truth.
//! this crate holds only the cross-layer contract: the trait, [`Span`],
//! [`Severity`], [`Code`], the per-crate accumulator [`Sink`], and the boxed
//! [`Diag`] carrier the binary renders.
//!
//! position in the crate graph: above `syntax` (it needs [`SyntaxNodePtr`] for
//! [`Span::Ptr`]), below lexer/parser/hir. not the very bottom - `token` stays
//! below it, so the lexer's logos callbacks carry no diagnostics dependency.

use std::borrow::Cow;
use std::fmt;

use syntax::{SyntaxNode, SyntaxNodePtr};
use text_size::TextRange;

/// a typed diagnostic kind. implemented by each layer's kind enum. the primary
/// message is the [`Display`](fmt::display) rendering; the primary span is
/// supplied separately at emit time (see [`Sink::emit`]) and travels in
/// [`Diag`].
pub trait Diagnostic: fmt::Display + fmt::Debug {
    /// stable, self-documenting error code (class letter + number).
    fn code(&self) -> Code;
    /// defaults to [`Severity::Error`]; warnings override.
    fn severity(&self) -> Severity {
        Severity::Error
    }
    /// extra labelled spans beyond the primary. default none.
    fn secondary_labels(&self) -> Vec<(Span, Cow<'static, str>)> {
        Vec::new()
    }
    /// free-standing notes. default none.
    fn notes(&self) -> Vec<Cow<'static, str>> {
        Vec::new()
    }
    /// a single actionable hint. default none.
    fn help(&self) -> Option<Cow<'static, str>> {
        None
    }
}

/// where a diagnostic points. lexer and parser produce byte [`TextRange`]s;
/// HIR produces a [`SyntaxNodePtr`] because ranges shift across edits.
#[derive(Debug, Clone)]
pub enum Span {
    Range(TextRange),
    Ptr(SyntaxNodePtr),
}

/// two spans compare by the byte range they cover (a `SyntaxNodePtr` carries its
/// range, so this needs no tree). manual because rowan's typed `SyntaxNodePtr`
/// is not `Eq`; lets diagnostics that carry an optional decl span stay `Eq`.
impl PartialEq for Span {
    fn eq(&self, other: &Self) -> bool {
        self.text_range() == other.text_range()
    }
}
impl Eq for Span {}

impl Span {
    /// the byte range this span covers, resolving a pointer if needed.
    pub fn text_range(&self) -> TextRange {
        match self {
            Span::Range(r) => *r,
            Span::Ptr(p) => p.text_range(),
        }
    }

    /// the byte range to underline, ready for display. a [`Span::Ptr`] names a
    /// tree node whose range includes the leading and trailing trivia the
    /// lossless tree attaches to a node's edges; given the parse `root` it is
    /// resolved and trimmed to its first..last non-trivia token via
    /// [`syntax::trimmed_text_range`]. a [`Span::Range`] (lexer/parser) is
    /// already a tight token range and is returned unchanged, so `root` may be
    /// `None` before a tree exists. every rendering edge (the CLI renderer and
    /// the language server) calls this, so the trim has one definition.
    pub fn trimmed_range(&self, root: Option<&SyntaxNode>) -> TextRange {
        match (self, root) {
            (Span::Ptr(p), Some(root)) => syntax::trimmed_text_range(&p.to_node(root)),
            _ => self.text_range(),
        }
    }
}

impl From<TextRange> for Span {
    fn from(r: TextRange) -> Self {
        Span::Range(r)
    }
}

impl From<SyntaxNodePtr> for Span {
    fn from(p: SyntaxNodePtr) -> Self {
        Span::Ptr(p)
    }
}

/// diagnostic severity. warnings are reported but do not fail a build.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
}

/// the error class. the letter prefix sorts and groups codes by concern; the
/// nine classes are the locked partition from `docs/features/DIAGNOSTICS.md`
/// (`Effect` is the ninth, the machine-EFFECT contract, EFFECT.md).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Class {
    Lex,
    Syntax,
    Grammar,
    Resolve,
    Type,
    Pattern,
    Const,
    Effect,
    Unsupported,
}

impl Class {
    /// the single-letter code prefix for this class.
    pub fn prefix(self) -> char {
        match self {
            Class::Lex => 'L',
            Class::Syntax => 'S',
            Class::Grammar => 'G',
            Class::Resolve => 'R',
            Class::Type => 'T',
            Class::Pattern => 'P',
            Class::Const => 'C',
            Class::Effect => 'E',
            Class::Unsupported => 'U',
        }
    }
}

/// a stable error code: class letter + zero-padded number, e.g. `R001`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Code {
    pub class: Class,
    pub number: u16,
}

impl Code {
    pub const fn new(class: Class, number: u16) -> Self {
        Code { class, number }
    }
}

impl fmt::Display for Code {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}{:03}", self.class.prefix(), self.number)
    }
}

/// per-crate accumulator. stores concrete typed entries so in-crate tests can
/// `matches!` a variant without downcasting. never halts a pass.
#[derive(Debug, Clone)]
pub struct Sink<K> {
    entries: Vec<(Span, K)>,
}

impl<K> Default for Sink<K> {
    fn default() -> Self {
        Sink {
            entries: Vec::new(),
        }
    }
}

impl<K> Sink<K> {
    pub fn new() -> Self {
        Sink::default()
    }

    /// record a diagnostic anchored at `span`.
    pub fn emit(&mut self, span: impl Into<Span>, kind: K) {
        self.entries.push((span.into(), kind));
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// concrete typed entries, for in-crate assertions.
    pub fn entries(&self) -> &[(Span, K)] {
        &self.entries
    }

    /// drain another sink of the same kind into this one (by value, move).
    pub fn extend(&mut self, other: Sink<K>) {
        self.entries.extend(other.entries);
    }

    /// keep only entries whose kind satisfies `keep`. used at the binary edge to
    /// suppress a specific diagnostic under a feature flag without modifying the
    /// pass that produced it.
    pub fn retain(&mut self, mut keep: impl FnMut(&K) -> bool) {
        self.entries.retain(|(_, kind)| keep(kind));
    }
}

impl<K: Diagnostic + 'static> Sink<K> {
    /// box every entry into the cross-layer [`Diag`] carrier the binary renders.
    pub fn into_diags(self) -> Vec<Diag> {
        self.entries
            .into_iter()
            .map(|(span, kind)| Diag {
                span,
                kind: Box::new(kind),
            })
            .collect()
    }
}

impl<K> IntoIterator for Sink<K> {
    type Item = (Span, K);
    type IntoIter = std::vec::IntoIter<(Span, K)>;
    fn into_iter(self) -> Self::IntoIter {
        self.entries.into_iter()
    }
}

/// a boxed diagnostic plus its primary span. the cross-layer carrier: phases
/// produce a [`Sink<K>`]; the binary collects `Vec<Diag>` and renders.
pub struct Diag {
    pub span: Span,
    pub kind: Box<dyn Diagnostic>,
}

impl Diag {
    pub fn new(span: impl Into<Span>, kind: impl Diagnostic + 'static) -> Self {
        Diag {
            span: span.into(),
            kind: Box::new(kind),
        }
    }
}

impl fmt::Debug for Diag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Diag")
            .field("span", &self.span)
            .field("code", &self.kind.code())
            .field("message", &self.kind.to_string())
            .finish()
    }
}
